hw_site/hw_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

hw_site/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>', views.main, name="root_paginate"),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('delete/<int:id_>/', views.delete_quote, name='delete_quote'),
    path('author/<str:id_>/', views.author_detail, name='author_detail'),
]

hw_site/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_site/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.fullname
    
class Tag(models.Model):
    name = models.CharField(max_length=120, null=False, unique=True)
    
    def __str__(self):
        return self.name
    
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw_site/quotes/forms.py
from django import forms
from .models import Author, Tag, Quote

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

hw_site/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag

from bson import ObjectId
from .utils import get_mongodb

# # Create your views here.
def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})
# def main(request, page=1):
#     quotes = Quote.objects.all()
#     per_page = 10
#     paginator = Paginator(quotes, per_page)
#     quotes_on_page = paginator.get_page(page)
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    else:
        form = AuthorForm()
    
    return render(request, 'quotes/add_author.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote_text = form.cleaned_data['quote']
            author = form.cleaned_data['author']

            tags_input = str(form.cleaned_data['tags'])

            tags_list = [tag.strip() for tag in tags_input.split(',')]
            
            tags = [Tag.objects.get_or_create(name=tag_name)[0] for tag_name in tags_list]

            quote = Quote(quote=quote_text, author=author)
            quote.save()
            # for tag in tags:
            #     quote.tags.add(tag)
            tags_to_add = [tag for tag in tags if tag not in quote.tags.all()]
            quote.tags.add(*tags_to_add)

            return redirect(reverse('quotes:root'))

    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})



@login_required
def delete_quote(request, id_):
    try:
        quote = Quote.objects.get(id=id_)
        quote.delete()
    except Quote.DoesNotExist:
        pass
    return redirect('quotes:root')


# def author_detail(request, id_):
#     author = get_object_or_404(Author, id=id_)
#     return render(request, 'quotes/author_detail.html', context={'author': author})

def author_detail(request, id_):
    db = get_mongodb()
    author = db.authors.find_one({'_id': ObjectId(id_)})
    return render(request, 'quotes/author_detail.html', context={'author': author})

hw_site/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Add author</h1>

{% if messages %}
{% for message in messages%}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {{ form.non_field_errors}}
</div>
{% endif %}

<form action="{% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary type="submit">Add author</button>
  </form>
{% endblock %}

hw_site/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Add quote</h1>

{% if messages %}
{% for message in messages%}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}
  role="alert">
  {{message}}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
  {% csrf_token %}
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.quote.id_for_label }}">Quote:</span>
      {{ form.quote }}
  </div>
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.tags.id_for_label }}">Tags (comma-separated):</span>
      {{ form.tags }}
  </div>
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.author.id_for_label }}">Author:</span>
      {{ form.author }}
  </div>
  <button class="btn btn-primary" type="submit">Add quote</button>
</form>
{% endblock %}

hw_site/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
  <div class="author-detail">
    <h1>{{ author.fullname }}</h1>
    <p class="author-birthdate">Birthdate: {{ author.born_date }} in {{ author.born_location }}</p>
    <p class="author-bio">{{ author.description }}</p>
  </div>
{% endblock %}

hw_site/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HW Site</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                        <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                        <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
                    {% else %}
                        <a href="{% url 'users:signup' %}" class="btn btn-primary">SingUp</a>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>
    
    {% block content %} {% endblock %}

    </div>
</body>
</html>

hw_site/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}

            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world"> 
                {% for tags_list in quote.tags %}
                {% for tag in tags_list %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
                {% endfor %}
            </div>

        </div>
            {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}" href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                </li>
            </ul>
        </nav>
        </div>
    </div>

</div>

{% endblock %}